name: My workflow
permissions:
  actions: read
  contents: write
  checks: write
  pull-requests: write
on: 
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true 
    # Begin AppMap CI language agent installation.
    # This snippet can be safely removed once the AppMap language agent has been
    # added to the project dependencies, and appmap.yml has been created.
    - name: Enable appmap gem update
      run: bundle config unset deployment
    - name: Install AppMap tools
      id: install-appmap
      uses: getappmap/install-action@v1
      with:
        project-type: bundler
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "ci: Add AppMap language agent and appmap.yml"
    # End AppMap CI language agent installation
    - run: bundle exec rspec
    - name: Save AppMaps
      uses: actions/cache/save@v3
      if: always()
      with:
        path: ./tmp/appmap
        key: appmaps-${{ github.sha }}-${{ github.run_attempt }}

  appmap-analysis:
    if: always()
    needs: [test] # You may need to change this to match
                  # the name of the step that runs your tests.
    uses: getappmap/analyze-action/.github/workflows/appmap-analysis.yml@v1
    permissions:
      actions: read
      contents: write
      checks: write
      pull-requests: write